import { Link } from "wouter";
const BRAND = "/manus-storage/PhoennixAI_16d880ee.jpg";

type Section = { id: string; title: string; body: string[] };
const privacy: Section[] = [
  { id: "collect", title: "1. What we collect", body: ["When you join the Kaizen OS waitlist, we collect the information you choose to provide in the form. Required details are your first name and email address. Company or organisation and role are optional.", "We record whether you accepted the waitlist terms and whether you opted in to optional product news. Please do not submit sensitive personal information through the form."] },
  { id: "why", title: "2. Why we use it", body: ["We use the information to manage early access, send confirmation and invitation messages, understand at a high level who is interested when optional details are supplied, and respond to requests about the waitlist.", "Optional product-news emails are separate from operational confirmation and invitation emails."] },
  { id: "basis", title: "3. Lawful basis", body: ["Before launch, PhoennixAI must document the lawful basis for each processing purpose. Where direct marketing rules require consent, the optional marketing preference must be kept separate, clear and recorded."] },
  { id: "share", title: "4. Who may receive it", body: ["Access is limited to authorised PhoennixAI operators and service providers required to run the waitlist. The initial implementation uses Microsoft 365 services: Excel Online, Power Automate and Outlook."] },
  { id: "retain", title: "5. Retention", body: ["Waitlist information is retained only for as long as reasonably necessary to manage early access and maintain appropriate records. It is then deleted or anonymised unless a longer period is required for a specific legal or operational reason."] },
  { id: "rights", title: "6. Your rights", body: ["Depending on the circumstances and lawful basis used, you may have rights including access, correction, deletion, restriction, objection and data portability. You can ask to be removed from the waitlist."] },
  { id: "contact", title: "7. Contact", body: ["For privacy questions, access requests or removal requests, use the PhoennixAI privacy contact published on the production site. Replace this launch-draft placeholder with final legal entity and contact details before public release."] }
];
const terms: Section[] = [
  { id: "joining", title: "1. Joining the waitlist", body: ["By submitting the Kaizen OS waitlist form, you register interest in receiving information about the product and possible early access.", "Joining is not a purchase. It does not create a paid subscription, service contract or guaranteed entitlement to Kaizen OS."] },
  { id: "access", title: "2. Early access", body: ["Kaizen OS may be released in stages. Invitations may be offered when the product is ready for a relevant early-access group.", "Joining does not guarantee access, a particular launch date, feature set or continued availability of early access."] },
  { id: "communications", title: "3. Communications", body: ["We may send operational messages about your request, including confirmation and invitation information. Optional product-news emails are sent only in line with the preference provided and applicable rules."] },
  { id: "information", title: "4. Information you provide", body: ["You are responsible for providing information that is accurate and current enough for us to manage your request. Do not submit sensitive personal information through the waitlist form."] },
  { id: "ip", title: "5. Product and intellectual property", body: ["The Kaizen OS name, concepts, interface designs, software, branding and related materials are owned by, licensed to, or being developed for PhoennixAI or their respective rights holders. Joining grants no ownership or licence."] },
  { id: "changes", title: "6. Changes and cancellation", body: ["We may change, pause or close the waitlist as the product develops. The current terms are published on this page."] },
  { id: "contact", title: "7. Contact", body: ["Questions about the waitlist should be directed to the PhoennixAI contact published on the production site. Replace this placeholder with final legal details and obtain appropriate legal review before public launch."] }
];

export default function Legal({ kind }: { kind: "privacy" | "terms" }) {
  const isPrivacy = kind === "privacy"; const sections = isPrivacy ? privacy : terms; const title = isPrivacy ? "Privacy" : "Waitlist"; const em = isPrivacy ? "notice" : "terms";
  return <div className="legal"><div className="site-shell"><header className="site-header"><Link className="brand" href="/"><span className="brand-mark"><img src={BRAND} alt="PhoennixAI phoenix mark" /></span><span className="brand-type">PhoennixAI<small>Kaizen OS · Early access</small></span></Link><Link className="launch-pill" href="/">Back to waitlist</Link></header><main><header className="legal-hero"><p className="eyebrow">Kaizen OS · Early access</p><h1>{title} <em>{em}</em></h1><p className="legal-intro">{isPrivacy ? "This notice explains how PhoennixAI handles personal information collected through the Kaizen OS early-access waitlist." : "These terms explain what it means to join the Kaizen OS early-access waitlist operated by PhoennixAI."}</p><p className="legal-meta">Last updated: 23 September 2026 · Launch draft</p></header><div className="legal-layout"><nav className="toc"><strong>On this page</strong>{sections.map((section) => <a key={section.id} href={`#${section.id}`}>{section.title.replace(/^\d+\. /, "")}</a>)}</nav><article>{sections.map((section) => <section id={section.id} key={section.id}><h2>{section.title}</h2>{section.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</section>)}</article></div></main><footer className="site-footer"><span>PhoennixAI · Kaizen OS</span><span className="footer-links"><Link href="/">Waitlist</Link><Link href={isPrivacy ? "/terms" : "/privacy"}>{isPrivacy ? "Waitlist terms" : "Privacy notice"}</Link></span></footer></div></div>;
}
